#define NETSTACK_CONF_RDC	nullrdc_driver
//#define NETSTACK_CONF_RDC	contikimac_driver
//#define CONTIKIMAC_CONF_CYCLE_TIME 1666
#define NETSTACK_CONF_MAC	nullmac_driver
#define CLOCK_CONF_SECOND	512

#define NETSTACK_CONF_FRAMER framer_802154 //ssma


#define NULLRDC_CONF_ADDRESS_FILTER	0 //ssma
#define TlIMESYNCH_CONF_ENABLED	0
#define NULLRDC_802154_AUTOACK	0
#define CC2420_CONF_TIMESTAMPS	0
#define RDC_WITH_DUPLICATE_DETECTION	1

#define CC2420_CONF_AUTOACK		0

//#define RTIMER_CONF_SECOND	32768

#define UIP_CONF_TCP 0
#define UIP_CONF_UDP 0
#define UIP_CONF_BROADCAST 0
#define PROCESS_CONF_NO_PROCESS_NAMES 1

#define SHORTEST_PACKET_SIZE 0

#define USE_CC2630_CONFIG 1

#define RADIO_CC2420_CONFIG 0

#define RADIO_CC2630_CONFIG 1
